/**
 * Rebrand the repository from DeepSeek to Voyaseek, and re-apply that rebrand
 * after every upstream pull of the open-source harness. The mapping is an
 * ordered rule table plus a protection list, so a fresh upstream snapshot can
 * be rebranded by re-running one command instead of repeating a manual sweep
 * ([rationale](../.agents/notes/implemented/feature/2026-08-17-voyaseek-brand-migration.md)).
 *
 * Rules are plain substring replacements applied longest-first, so specific
 * forms (repository URLs) win over generic ones (`deepseek-harness`). Every
 * replacement is free of its own pattern, which makes the pass idempotent: a
 * second `--apply` is a no-op, and `--check` asserts exactly that plus zero
 * residue outside the protection list.
 *
 * The protection list shields what a rebrand must never rewrite: the DeepSeek
 * API contract (`api.deepseek.com`, `DEEPSEEK_API_KEY`, the `deepseek-official`
 * provider id, `deepseek-v*` model ids — none of these match any rule),
 * upstream provenance (vendored-package repository URLs, masked inline so the
 * rest of the file still rebrands), MIT legal attribution (`LICENSE`, `legal/`,
 * `THIRD_PARTY_NOTICES.md` — regenerated from the vendored manifest instead),
 * frozen Agent Notes, and generated lockfiles (regenerated by installs).
 *
 * Usage: `pnpm run rebrand [--apply|--check]`. Without a mode it reports what
 * would change. After `--apply`, run `pnpm install`, regenerate
 * `THIRD_PARTY_NOTICES.md`, and re-record the translation-pairing manifest.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, realpathSync, renameSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(import.meta.dirname, '..')

/** One ordered substring replacement; earlier rules win over later ones. */
interface Rule {
  readonly id: string
  readonly find: string
  readonly replace: string
  /** Tracked-path prefixes this rule must not touch (API-vendor attribution lives there). */
  readonly skip?: readonly string[]
}

/**
 * The rebrand mapping, in application order. Repository URLs come before the
 * bare host, the scoped package prefix before the generic harness slug, and
 * every `deepseek-harness` form before the bare company mention, so no rule
 * can partially consume another's match.
 */
const RULES: readonly Rule[] = [
  { id: 'repo-url-ai', find: 'github.com/deepseek-ai/deepseek-harness', replace: 'github.com/voyaseek-ai/voyaseek-harness' },
  { id: 'repo-url-self', find: 'github.com/deepseek-harness/deepseek-harness', replace: 'github.com/voyaseek-ai/voyaseek-harness' },
  { id: 'repo-url-raw', find: 'raw.githubusercontent.com/deepseek-ai/deepseek-harness', replace: 'raw.githubusercontent.com/voyaseek-ai/voyaseek-harness' },
  { id: 'repo-host', find: 'github.com/deepseek-ai', replace: 'github.com/voyaseek-ai' },
  { id: 'npm-scope', find: '@deepseek-ai', replace: '@voyaseek-ai' },
  { id: 'camel', find: 'DeepSeekHarness', replace: 'VoyaseekHarness' },
  { id: 'snake', find: 'deepseek_harness', replace: 'voyaseek_harness' },
  { id: 'upper', find: 'DEEPSEEK_HARNESS', replace: 'VOYASEEK_HARNESS' },
  { id: 'slug', find: 'deepseek-harness', replace: 'voyaseek-harness' },
  { id: 'prose', find: 'DeepSeek Harness', replace: 'Voyaseek Harness' },
  { id: 'company', find: 'DeepSeek AI', replace: 'Voyaseek AI' },
  { id: 'telemetry-domain', find: 'deepseeksvc.com', replace: 'voyaseeksvc.com' },
  { id: 'brand-token', find: '--dsw-static-deepseek-450', replace: '--dsw-static-voyaseek-450' },
  { id: 'blog-url', find: 'https://www.deepseek.com/blog/harness-architecture', replace: 'https://www.voyaseek.com/blog/harness-architecture' },
  { id: 'docs-url', find: 'https://docs.deepseek.com/harness/plugins', replace: 'https://docs.voyaseek.com/harness/plugins' },
  { id: 'company-link', find: '[DeepSeek](https://www.deepseek.com)', replace: '[Voyaseek](https://www.voyaseek.com)' },
  {
    id: 'company-site',
    find: 'https://deepseek.com',
    replace: 'https://voyaseek.com',
    // The web-search provider's README names the actual API vendor on purpose.
    skip: ['packages/web/web-search-deepseek/'],
  },
  { id: 'home-env', find: 'DSH_HOME', replace: 'VOYASEEK_HOME' },
]

/**
 * Inline-masked provenance: vendored packages record their true upstream
 * repository, and the self-URL (`.../deepseek-harness/deepseek-harness`) is
 * handled by `repo-url-self`, so the mask shields only sibling repositories
 * (cosmokit, schemastery, cordis, turtle-ui) from the generic `slug` rule.
 */
const MASKS: readonly RegExp[] = [
  /github\.com\/deepseek-harness\/(?!deepseek-harness)[\w.-]+/g,
]

/** The home directory token: `.dsh` as a path segment, never `.dshHome`, `.dsh-e2b`, or `.dsh_session_id`. */
const HOME_DIR_PATTERN = /(?<![A-Za-z0-9])\.dsh(?![A-Za-z0-9_.-])/g
const HOME_DIR_REPLACEMENT = '.voyaseek'

/** Tracked file/directory renames the rebrand performs; API-vendor and legal names stay. */
const RENAMES: readonly { from: string; to: string }[] = [
  { from: 'python/sdk/src/deepseek_harness', to: 'python/sdk/src/voyaseek_harness' },
  { from: 'python/sdk-runtime/src/deepseek_harness_runtime', to: 'python/sdk-runtime/src/voyaseek_harness_runtime' },
  { from: 'python/sdk-runtime/src/voyaseek_harness_runtime/deepseek-harness-runtime.json', to: 'python/sdk-runtime/src/voyaseek_harness_runtime/voyaseek-harness-runtime.json' },
]

const EXTENSIONS = [
  '.ts', '.tsx', '.js', '.mjs', '.cjs', '.json', '.jsonl', '.yml', '.yaml', '.md',
  '.py', '.toml', '.txt', '.html', '.css', '.c', '.h', '.sh', '.tpl', '.xml', '.svg',
  '.webmanifest', '.snap',
] as const

/** Files and directories the rebrand must never rewrite. */
function excluded(file: string): boolean {
  if (file === 'scripts/rebrand.ts' || file === 'scripts/rebrand.spec.ts') return true // the mapping itself
  if (file.startsWith('.agents/notes/')) return true // frozen archive
  if (file === 'LICENSE') return true // MIT copyright names the upstream author
  if (file.startsWith('apps/aistaff-desktop/legal/')) return true // legal attribution travels verbatim
  if (file === 'THIRD_PARTY_NOTICES.md') return true // regenerated from vendor/README.md
  if (file === '.open-source/adoptions.yaml') return true // upstream provenance registry
  if (file === 'pnpm-lock.yaml') return true // regenerated by pnpm install
  if (file === 'apps/aistaff-desktop/package-lock.json') return true // regenerated by npm install
  if (file.endsWith('.i18n.yaml')) return true // blob-hash records, re-recorded by the pairing gate
  return !EXTENSIONS.some(extension => file.endsWith(extension))
}

/** Mask protected provenance substrings with NUL sentinels no rule can match. */
function mask(text: string): { text: string; saved: string[] } {
  const saved: string[] = []
  let out = text
  for (const pattern of MASKS) {
    out = out.replace(pattern, (match) => {
      saved.push(match)
      return `\u0000${String(saved.length - 1)}\u0000`
    })
  }
  return { text: out, saved }
}

function unmask(text: string, saved: readonly string[]): string {
  return text.replace(/\u0000(\d+)\u0000/g, (_match, index: string) => saved[Number(index)] ?? '')
}

/** Apply every rule and the home-directory token to one file's text. */
export function rebrand(text: string, file: string): { text: string; hits: number } {
  const masked = mask(text)
  let out = masked.text
  let hits = 0
  for (const rule of RULES) {
    if (rule.skip?.some(prefix => file.startsWith(prefix))) continue
    const count = out.split(rule.find).length - 1
    if (count > 0) {
      out = out.split(rule.find).join(rule.replace)
      hits += count
    }
  }
  out = out.replace(HOME_DIR_PATTERN, () => {
    hits += 1
    return HOME_DIR_REPLACEMENT
  })
  return { text: unmask(out, masked.saved), hits }
}

/**
 * Residue patterns for `--check`: any surviving occurrence outside an excluded
 * file means the mapping missed a form. API-vendor names (`api.deepseek.com`,
 * `DEEPSEEK_API_KEY`, `deepseek-official`, `llm-deepseek`, `deepseek-v*`,
 * `web-search-deepseek`, `onboarding-deepseek-config`, `DeepSeek*Editor`) are
 * product data and intentionally absent from this list.
 */
const RESIDUE: readonly RegExp[] = [
  /@deepseek-ai/,
  /[Dd]eep[Ss]eek[-_ ][Hh]arness/,
  /DEEPSEEK_HARNESS/,
  /deepseeksvc\.com/,
  /github\.com\/deepseek-ai/,
  /DeepSeek AI/,
  /DSH_HOME/,
  /(?<![A-Za-z0-9])\.dsh(?![A-Za-z0-9_.-])/,
  /--dsw-static-deepseek-/,
  /https:\/\/(?:www\.|docs\.)?deepseek\.com\/(blog|harness)/,
]

function main(): void {
  const args = process.argv.slice(2)
  const mode = args.includes('--apply') ? 'apply' : args.includes('--check') ? 'check' : 'dry'
  const files = execFileSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8' })
    .split('\0')
    .filter(file => file !== '' && !excluded(file))

  const changed: string[] = []
  const failures: string[] = []
  let hits = 0
  for (const file of files) {
    const path = resolve(root, file)
    const before = readFileSync(path, 'utf8')
    const { text: after, hits: fileHits } = rebrand(before, file)
    if (mode === 'check') {
      for (const pattern of RESIDUE) {
        if (pattern.test(mask(after).text)) {
          failures.push(`residue: ${file} still matches ${pattern.source}`)
        }
      }
    }
    if (after === before) continue
    changed.push(file)
    hits += fileHits
    if (mode === 'apply') writeFileSync(path, after)
  }

  console.log(`rebrand: ${mode} over ${String(files.length)} tracked files: ${String(changed.length)} file(s), ${String(hits)} replacement(s)`)
  if (mode === 'dry') {
    for (const file of changed.slice(0, 40)) console.log(`  would rewrite ${file}`)
    if (changed.length > 40) console.log(`  … and ${String(changed.length - 40)} more`)
  }

  if (mode === 'apply') {
    for (const rename of RENAMES) {
      const from = resolve(root, rename.from)
      const to = resolve(root, rename.to)
      if (!existsSync(from)) continue
      if (existsSync(to)) {
        failures.push(`rename target already exists: ${rename.to}`)
        continue
      }
      renameSync(from, to)
      console.log(`  renamed ${rename.from} -> ${rename.to}`)
    }
  }

  if (mode === 'check') {
    for (const rename of RENAMES) {
      if (existsSync(resolve(root, rename.from))) failures.push(`rename pending: ${rename.from} still exists`)
    }
    for (const file of changed) failures.push(`not idempotent or unapplied: ${file}`)
  }

  if (failures.length > 0) {
    for (const failure of failures.slice(0, 60)) console.error(`rebrand: ${failure}`)
    console.error(`rebrand: ${String(failures.length)} problem(s).`)
    process.exitCode = 1
  } else if (mode === 'check') {
    console.log('rebrand: post-state verified — no residue, renames landed, idempotent.')
  } else if (mode === 'apply') {
    console.log('rebrand: applied. Run `pnpm install`, regenerate THIRD_PARTY_NOTICES.md, and re-record the translation-pairing manifest.')
  }
}

// Importing this module for its exported rewriter must not run the codemod.
if (process.argv[1] !== undefined && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  main()
}
